server:
  servlet:
    context-path: /pc
spring:
  application:
    name: product-catalog-api
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false
      key-prefix: true
      use-key-prefix: true
  data:
    redis:
      host: localhost
      port: 6379
      password: # Add password if required